### ISSUE TITLE
Outdated Node version

### ISSUE THREAD

**Issue by rpaulucci3** [Microsoft/pxt-rpi#1]
The version of Node.js used in the install script for this repo is 6.x, which has been EOL for a long time.

The official documentation (https://makecode.microbit.org/raspberry-pi) references this script.

**Comment by pelikhan** [comment]
Thanks for pointing this out. We'll update.

**Comment by rpaulucci3** [comment]
Fixed in PR #3. Merci, M. de Halleux !

**Comment by pelikhan** [comment]
Merci - on a pas beaucoup travailler sur le pi. On apprecie l’aide!
